# Generated by Django 3.1 on 2020-09-11 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prelaunch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prelaunch',
            new_name='PrelaunchModel',
        ),
    ]
